## Some losses in Keras

https://keras.io/losses/

In [1]:
try: #If running in colab 
    import google.colab
    IN_COLAB = True 
    %tensorflow_version 2.x
except:
    IN_COLAB = False

In [2]:
import tensorflow as tf
if (not tf.__version__.startswith('2')): #Checking if tf 2.0 is installed
    print('Please install tensorflow 2.0 to run this notebook')
print('Tensorflow version: ',tf.__version__, ' running in colab?: ', IN_COLAB)

Tensorflow version:  2.0.0  running in colab?:  False


In [3]:
from tensorflow.keras import losses

### The categorical cross entropy

In [40]:
import tensorflow.keras as keras
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from tensorflow.keras.utils import to_categorical 

In [41]:
y_true_sp = [0,1,1,2]
y_true_one_hot = to_categorical(y_true_sp)
y_pred = np.array([
    [0.9,0.1,0],   #each row must sum up to one
    [0.0,0.5,0.5],
    [0.1,0.3,0.6],
    [0.2,0.1,0.7]
])
print(y_pred) 
y_true_one_hot

[[0.9 0.1 0. ]
 [0.  0.5 0.5]
 [0.1 0.3 0.6]
 [0.2 0.1 0.7]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [42]:
idx = np.asarray(y_true_one_hot, dtype=np.bool)
idx

array([[ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True]])

In [43]:
y_pred[idx],-np.log(y_pred[idx]),-np.mean(np.log(y_pred[idx]))

(array([0.9, 0.5, 0.3, 0.7]),
 array([0.10536052, 0.69314718, 1.2039728 , 0.35667494]),
 0.58978886112061)

In [46]:
losses.categorical_crossentropy(y_true_one_hot, y_pred)

<tf.Tensor: id=135, shape=(4,), dtype=float64, numpy=array([0.10536052, 0.69314718, 1.2039728 , 0.35667494])>

### 